<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="皮卡丘的大脑" name="smoke" tests="9" failures="1" timestamp="23 Nov 2019 10:34:28 GMT" time="0.089" errors="0">
  <testcase name="testAngleFunc" time="0.043" classname="com.sadie.JudgeTrangleTest"/>
  <testcase name="testFunction" time="0.002" classname="com.sadie.JudgeTrangleTest"/>
  <testcase name="testClear" time="0.0" classname="com.util.MySumOfSquaresTest"/>
  <testcase name="testCopy" time="0.0" classname="com.util.MySumOfSquaresTest"/>
  <testcase name="testCopyForSourceDest" time="0.0" classname="com.util.MySumOfSquaresTest"/>
  <testcase name="testEvaluate" time="0.001" classname="com.util.MySumOfSquaresTest">
    <failure type="java.lang.AssertionError" message="expected [37.0] but found [38.0]">
      <![CDATA[java.lang.AssertionError: expected [37.0] but found [38.0]
	at com.util.MySumOfSquaresTest.testEvaluate(MySumOfSquaresTest.java:81)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testEvaluate -->
  <testcase name="testGetN" time="0.001" classname="com.util.MySumOfSquaresTest"/>
  <testcase name="testGetResult" time="0.0" classname="com.util.MySumOfSquaresTest"/>
  <testcase name="testIncrement" time="0.0" classname="com.util.MySumOfSquaresTest"/>
</testsuite> <!-- smoke -->
